app/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from . import db, login_manager


class Data(db.Model):
    id = db.Column(db.INTEGER, primary_key=True)
    first_name = db.Column(db.String(100))
    middle_initial = db.Column(db.String(100))
    last_name = db.Column(db.String(100))
    date_of_birth = db.Column(db.Date)
    age = db.Column(db.INTEGER)
    home_town = db.Column(db.String(100))
    height = db.Column(db.INTEGER)
    weight = db.Column(db.INTEGER)
    scout_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    def __init__(self, first_name, middle_initial, last_name, date_of_birth, age, home_town, height, weight):
        self.first_name = first_name
        self.middle_initial = middle_initial
        self.last_name = last_name
        self.date_of_birth = date_of_birth
        self.age = age
        self.home_town = home_town
        self.height = height
        self.weight = weight


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(64), unique=True, index=True)
    username = db.Column(db.String(64), unique=True, index=True)
    scout = db.Column(db.Boolean, index=True)
    password_hash = db.Column(db.String(128))

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return '<User %r>' % self.username


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, PasswordField, SubmitField, validators, BooleanField, IntegerField, DateField
from wtforms.validators import DataRequired, Email, InputRequired, NumberRange


class PlayerForm(FlaskForm):
    first_name = StringField('First Name', [validators.DataRequired(), 
        validators.Length(min=1, max=100, message='Name length between 1 and 99')])
    middle_initial = StringField('Middle Initial', [validators.Optional(), 
        validators.Length(min=1, max=1, message='Only one character for initial')])
    last_name = StringField('Last Name', [validators.DataRequired(), 
        validators.Length(min=1, max=100, message='Name length between 1 and 99')])
    date_of_birth = DateField('Date of Birth (mm/dd/yyyy)', format='%m/%d/%Y')
    age = IntegerField('Age', [validators.DataRequired()])
    home_town = StringField('Home Town', [validators.Optional(), 
        validators.Length(min=1, max=100, message='Home town length between 1 and 99')])
    height = IntegerField('Height (in.)', [validators.DataRequired()])
    weight = IntegerField('Weight (lb.)', [validators.DataRequired()])
    submit = SubmitField('Add Player')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_mail import Mail
from flask_moment import Moment
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from config import config

bootstrap = Bootstrap()
mail = Mail()
moment = Moment()
db = SQLAlchemy()

login_manager = LoginManager()
login_manager.login_view = 'auth.login'


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    mail.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from flask import render_template, redirect, request, url_for, flash
from flask_login import login_required, current_user
from .. import db
from . import main
from ..models import Data, User
from .forms import PlayerForm



@main.route('/')
def index():
    return render_template('index.html')

@main.route('/scouts')
def Scouts():
    stats = Data.query.all()
    return render_template("scouts.html", stats=stats)


@main.route('/managers')
def Managers():
    stats = Data.query.all()
    return render_template("managers.html", stats=stats)


#Adds new player
@main.route('/addplayer', methods=['GET', 'POST'])
@login_required
def addplayer():
    form = PlayerForm()
    if form.validate_on_submit():
        player = Data(first_name=form.first_name.data,
                    middle_initial=form.middle_initial.data,
                    last_name=form.last_name.data,
                    date_of_birth=form.date_of_birth.data,
                    age=form.age.data,
                    home_town=form.home_town.data,
                    height=form.height.data,
                    weight=form.weight.data)
        db.session.add(player)
        db.session.commit()
        flash('Player Added.')
        return redirect(url_for('main.Scouts'))
    return render_template('player.html', form=form)

@main.route('/delete/<int:id>')
@login_required
def delete(id):
    deleting_item = Data.query.get_or_404(id)
    try:
    	db.session.delete(deleting_item)
    	db.session.commit()
    	return redirect(url_for('main.Scouts'))

    except:
    	return "couldn't delete that homie"

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Flasky{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">Flasky</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.index') }}">Home</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
                {% else %}
                <li><a href="{{ url_for('auth.login') }}">Log In</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
<script type="text/javascript" src="{{url_for('static', filename='js/jquery-3.2.1.js')}}"></script>

<script type="text/javascript" src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>
{% endblock %}

app/templates/header.html
{% extends 'base.html' %}



{% block title %} Scout Universe {% endblock %}



{% block body %}

<div class = "jumbotron p-3">
        <div class = "well text-center">
            <h1> Scout Universe </h1>
        </div>
</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block title %} Scout Universe {% endblock %}

{% block page_content %}

<div class = "jumbotron p-3">
    <div class = "well text-md-center">
        {% if current_user.is_authenticated %}
            {% if current_user.scout %}
                <h2><a href="/scouts">View and Edit Players</a></h2>
            {% else %}
                <h2><a href="/managers">View Players</a></h2>
            {% endif %}
        {% else %}
            Please log in to view players.
        {% endif %}
    </div>
</div>

{% endblock %}

app/templates/managers.html
{% extends "base.html" %}


{% block title %} Database {% endblock %}

{% block body %}

<div class = "container">
    <div class = "row">
        <div class = "col md-12">
            <div class = "jumbotron p-3">
                <h2>View Players</h2>

                <table class="table table-hover table-dark">
                    <tr>
                        <th>ID</th>
                        <th>First Name</th>
                        <th>Middle Initial</th>
                        <th>Last Name</th>
                        <th>Date of Birth</th>
                        <th>Age</th>
                        <th>Home Town</th>
                        <th>Height</th>
                        <th>Weight (lbs)</th>
                    </tr>
                    {% for player in stats %}
                    <tr>
                        <td>{{ player.id }}</td>
                        <td>{{ player.first_name }}</td>
                        <td>{{ player.middle_initial }}</td>
                        <td>{{ player.last_name }}</td>
                        <td>{{ player.date_of_birth }}</td>
                        <td>{{ player.age }}</td>
                        <td>{{ player.home_town }}</td>
                        <td>{{ player.height }}</td>
                        <td>{{ player.weight }}</td>
                    </tr>
                    {% endfor %}
</table>
</div>
<div>
    <a href="{{ url_for('main.index') }}">Go Home</a>
</div>



{% endblock %}

app/templates/player.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Add Player{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Add a new player</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/scouts.html
{% extends "base.html" %}


{% block title %} Database {% endblock %}

{% block body %}

<div class = "container">
    <div class = "row">
        <div class = "col md-12">
            <div class = "jumbotron p-3">
                <h2>Manage Players 
                    
                </h2>
                <a href="{{ url_for('main.addplayer') }}">Add New Player</a>

                <table class="table table-hover table-dark">
                    <tr>
                        <th>ID</th>
                        <th>First Name</th>
                        <th>Middle Initial</th>
                        <th>Last Name</th>
                        <th>Date of Birth</th>
                        <th>Age</th>
                        <th>Home Town</th>
                        <th>Height</th>
                        <th>Weight (lbs)</th>
                    </tr>
                    {% for player in stats %}
                    <tr>
                        <td>{{ player.id }}</td>
                        <td>{{ player.first_name }}</td>
                        <td>{{ player.middle_initial }}</td>
                        <td>{{ player.last_name }}</td>
                        <td>{{ player.date_of_birth }}</td>
                        <td>{{ player.age }}</td>
                        <td>{{ player.home_town }}</td>
                        <td>{{ player.height }}</td>
                        <td>{{ player.weight }}</td>
                        <td>
                            <a href="/delete/{{player.id}}" class="btn btn-danger btn-xs" onclick="return confirm('Are You Sure You Want To Delete?')">Delete</a>
                        </td>
                    </tr>
                    {% endfor %}
</table>
</div>
<div>
    <a href="{{ url_for('main.index') }}">Go Home</a>
</div>



{% endblock %}